import torch
import torch.nn as nn
from isaaclab.envs import ManagerBasedRLEnv
from isaaclab.managers import RewardTermCfg as RewTerm
from isaaclab.managers import SceneEntityCfg
import isaaclab_tasks.manager_based.manipulation.reach.mdp as mdp

# --- LLM GENERATED FUNCTIONS START ---
# This section will be populated by 1_eureka.py 
# using the functions generated by the LLM.

def ee_position_reward(env: ManagerBasedRLEnv, asset_cfg: SceneEntityCfg, command_name: str) -> torch.Tensor:
    """
    Reward for end-effector being close to the target position.
    """
    robot = env.scene[asset_cfg.name]
    ee_pos = robot.data.body_pos_w[:, asset_cfg.body_ids[0]]  # World-space end-effector position
    target_pos = env.command_manager.get_command(command_name)[:, :3]  # Target position (x, y, z)
    distance = torch.norm(target_pos - ee_pos, dim=-1)
    # Penalize distance heavily, but give a bonus if within tolerance
    reward = torch.exp(-distance * 10.0)  # Exponential decay, higher reward for closer distances
    return reward

def ee_orientation_reward(env: ManagerBasedRLEnv, asset_cfg: SceneEntityCfg, command_name: str) -> torch.Tensor:
    """
    Reward for end-effector having the correct orientation.
    """
    robot = env.scene[asset_cfg.name]
    ee_orn = robot.data.body_quat_w[:, asset_cfg.body_ids[0]]  # World-space end-effector orientation (quaternion)
    target_orn = env.command_manager.get_command(command_name)[:, 3:] # Target orientation (quaternion)
    
    # Calculate orientation difference (axis-angle)
    delta_orn = quat_mul(quat_inv(ee_orn), target_orn)
    # Angle difference is the magnitude of the axis-angle vector
    angle_diff = 2 * torch.atan2(torch.norm(delta_orn[:, :3], dim=-1), delta_orn[:, 3])
    
    # Reward is higher for smaller angle differences, up to a maximum of 1.0
    reward = torch.cos(angle_diff * 0.5) # Cosine of half the angle difference
    return reward

def action_rate_penalty(env: ManagerBasedRLEnv, asset_cfg: SceneEntityCfg, command_name: str) -> torch.Tensor:
    """
    Penalty for high joint velocities to encourage smooth motion.
    """
    robot = env.scene[asset_cfg.name]
    # The action is typically the desired joint velocities or torques
    # We'll use the norm of joint velocities as a proxy for action rate
    joint_vel = robot.data.joint_vel
    action_rate = torch.norm(joint_vel, dim=-1)
    
    # Penalize high action rates, with a maximum penalty
    penalty = torch.clamp(action_rate, max=2.0) # Clamp to avoid excessively large penalties
    return -penalty * 0.5 # Scale the penalty



# --- LLM GENERATED FUNCTIONS END ---

def get_reward_cfg(env_cfg, robot_ee_body_name: str):
    """
    This function is called by reach_task.py to inject 
    the generated rewards into the Environment Config.
    """
    
    # We define the specific rewards here based on what the LLM created.
    # The LLM will be instructed to provide a dictionary called 'generated_terms'
    
    reward_dict = {
    "ee_position": RewTerm(func=ee_position_reward, weight=1.0, params={"command_name": "ee_pose"}),
    "ee_orientation": RewTerm(func=ee_orientation_reward, weight=1.0, params={"command_name": "ee_pose"}),
    "action_rate": RewTerm(func=action_rate_penalty, weight=0.1), # Lower weight for penalty
}
    
    # Example of what the LLM should generate:
    # reward_dict = {
    #     "reaching_goal": RewTerm(
    #         func=rew_function_name, # One of the functions inserted above
    #         weight=1.0,
    #         params={"asset_cfg": SceneEntityCfg("robot", body_names=[robot_ee_body_name]), "command_name": "ee_pose"}
    #     ),
    # }
    
    return reward_dict

def compute_success(env: ManagerBasedRLEnv) -> torch.Tensor:
    """
    Standardized success check. Automatically finds the EE index 
    using the body name from the robot configuration.
    """
    # 1. Get Target
    target_pos = env.command_manager.get_command("ee_pose")[:, :3]
    
    # 2. Dynamic EE Indexing
    # Instead of hardcoding '0', we find the index of 'panda_hand' or 'ee_link'
    robot = env.scene["robot"]
    
    # This matches the 'ee_body_name' passed in from reach.yaml
    # We use a simple search or pass it through the env_cfg
    ee_name = env.cfg.robot_ee_body_name # We'll ensure this is set in get_reward_cfg
    ee_index, _ = robot.find_bodies(ee_name)
    
    # 3. Get World Position of that specific index
    ee_pos = robot.data.body_pos_w[:, ee_index[0]] 
    
    # 4. Calculate Distance and Return
    distance = torch.norm(target_pos - ee_pos, dim=-1)
    return (distance < 0.05).float()