"""
Domain Randomization configuration.

This file is auto-generated by 3_dr_eureka.py using template injection.
The LLM-generated parameter ranges are inserted below.

Each variable should be named `<param>_range` and contain a two-element list
[low, high]. eval_headless.py loads this file and applies these ranges as
event terms that sample fresh values on every episode reset.
"""

# INSERT EUREKA DR HERE