import torch
import torch.nn as nn
from isaaclab.envs import ManagerBasedRLEnv
from isaaclab.managers import RewardTermCfg as RewTerm
from isaaclab.managers import SceneEntityCfg
import isaaclab_tasks.manager_based.manipulation.reach.mdp as mdp

# --- LLM GENERATED FUNCTIONS START ---
# This section will be populated by 1_eureka.py 
# using the functions generated by the LLM.

def ee_reach_reward(env: ManagerBasedRLEnv, asset_cfg: SceneEntityCfg, command_name: str) -> torch.Tensor:
    """
    Reward for reaching the target end-effector position.
    """
    robot = env.scene[asset_cfg.name]
    ee_pos = robot.data.body_pos_w[:, asset_cfg.body_ids[0]]
    target_pos = env.command_manager.get_command(command_name)[:, :3]
    distance = torch.norm(target_pos - ee_pos, dim=-1)
    # Reward is inversely proportional to distance, scaled to be more significant
    return 1.0 / (distance + 0.1) # Adding epsilon to avoid division by zero and scale reward

def ee_orientation_reward(env: ManagerBasedRLEnv, asset_cfg: SceneEntityCfg, command_name: str) -> torch.Tensor:
    """
    Reward for achieving the target end-effector orientation.
    """
    robot = env.scene[asset_cfg.name]
    ee_rot = robot.data.body_rot_w[:, asset_cfg.body_ids[0]]
    target_rot = env.command_manager.get_command(command_name)[:, 3:] # Assuming target command contains orientation quaternion
    
    # Compute the difference in orientation (quaternion difference)
    # For simplicity, we'll use the dot product of quaternions as a measure of similarity.
    # A value close to 1 means similar orientation.
    # Note: A more robust approach would involve converting to rotation matrices and computing Frobenius norm,
    # or using axis-angle representation, but quaternion dot product is a good start.
    orientation_diff = torch.sum(ee_rot * target_rot, dim=-1)
    
    # Reward is higher when orientation_diff is closer to 1
    # We add 1 to orientation_diff (making it 0 to 2) and then subtract from 2 to get a reward (2 to 0)
    # where 2 is perfect alignment. Then scale it.
    return torch.clamp(orientation_diff, min=0.0, max=1.0) * 2.0 # Scale to 0-2, where 2 is perfect match

def action_rate_penalty(env: ManagerBasedRLEnv, asset_cfg: SceneEntityCfg) -> torch.Tensor:
    """
    Penalty for high joint velocities (jerk).
    """
    robot = env.scene[asset_cfg.name]
    # Penalize the squared magnitude of joint velocities
    joint_vel_sq = torch.sum(robot.data.joint_vel[:, :7] ** 2, dim=-1) # Ignoring gripper velocities
    return -joint_vel_sq * 0.01 # Small scaling factor to keep penalty in reasonable range

def success_metric(env: ManagerBasedRLEnv, asset_cfg: SceneEntityCfg, command_name: str) -> torch.Tensor:
    """
    Binary reward for achieving the goal (within tolerance).
    """
    robot = env.scene[asset_cfg.name]
    ee_pos = robot.data.body_pos_w[:, asset_cfg.body_ids[0]]
    target_pos = env.command_manager.get_command(command_name)[:, :3]

    distance = torch.norm(target_pos - ee_pos, dim=-1)
    
    # Tolerance for position
    pos_tolerance = 0.05 # 5cm

    # For orientation, we can check if the dot product is above a certain threshold
    ee_rot = robot.data.body_rot_w[:, asset_cfg.body_ids[0]]
    target_rot = env.command_manager.get_command(command_name)[:, 3:]
    orientation_diff = torch.sum(ee_rot * target_rot, dim=-1)
    orientation_tolerance = 0.98 # High threshold for orientation similarity

    # Success if both position and orientation are within tolerance
    success = ((distance < pos_tolerance) & (orientation_diff > orientation_tolerance)).float()
    
    # Give a large reward for success, zero otherwise
    return success * 10.0



# --- LLM GENERATED FUNCTIONS END ---

def get_reward_cfg(env_cfg, robot_ee_body_name: str):
    """
    This function is called by reach_task.py to inject 
    the generated rewards into the Environment Config.
    """
    
    # We define the specific rewards here based on what the LLM created.
    # The LLM will be instructed to provide a dictionary called 'generated_terms'
    
    reward_dict = {
    "ee_reach": RewTerm(func=ee_reach_reward, weight=1.0, params={"asset_cfg": SceneEntityCfg("franka", body_names=["panda_hand"]), "command_name": "ee_pose"}),
    "ee_orientation": RewTerm(func=ee_orientation_reward, weight=0.5, params={"asset_cfg": SceneEntityCfg("franka", body_names=["panda_hand"]), "command_name": "ee_pose"}),
    "action_rate": RewTerm(func=action_rate_penalty, weight=0.01, params={"asset_cfg": SceneEntityCfg("franka", body_names=["panda_hand"])}),
    "reach_success": RewTerm(func=success_metric, weight=10.0, params={"asset_cfg": SceneEntityCfg("franka", body_names=["panda_hand"]), "command_name": "ee_pose"}),
}
    
    # Example of what the LLM should generate:
    # reward_dict = {
    #     "reaching_goal": RewTerm(
    #         func=rew_function_name, # One of the functions inserted above
    #         weight=1.0,
    #         params={"asset_cfg": SceneEntityCfg("robot", body_names=[robot_ee_body_name]), "command_name": "ee_pose"}
    #     ),
    # }
    
    return reward_dict

def compute_success(env: ManagerBasedRLEnv) -> torch.Tensor:
    """
    Standardized success check. Automatically finds the EE index 
    using the body name from the robot configuration.
    """
    # 1. Get Target
    target_pos = env.command_manager.get_command("ee_pose")[:, :3]
    
    # 2. Dynamic EE Indexing
    # Instead of hardcoding '0', we find the index of 'panda_hand' or 'ee_link'
    robot = env.scene["robot"]
    
    # This matches the 'ee_body_name' passed in from reach.yaml
    # We use a simple search or pass it through the env_cfg
    ee_name = env.cfg.robot_ee_body_name # We'll ensure this is set in get_reward_cfg
    ee_index, _ = robot.find_bodies(ee_name)
    
    # 3. Get World Position of that specific index
    ee_pos = robot.data.body_pos_w[:, ee_index[0]] 
    
    # 4. Calculate Distance and Return
    distance = torch.norm(target_pos - ee_pos, dim=-1)
    return (distance < 0.05).float()