import torch
import torch.nn as nn
from isaaclab.envs import ManagerBasedRLEnv
from isaaclab.managers import RewardTermCfg as RewTerm
from isaaclab.managers import SceneEntityCfg
import isaaclab_tasks.manager_based.manipulation.reach.mdp as mdp

# --- LLM GENERATED FUNCTIONS START ---
# This section will be populated by 1_eureka.py 
# using the functions generated by the LLM.

def ee_position_reward(env: ManagerBasedRLEnv, asset_cfg: SceneEntityCfg, command_name: str) -> torch.Tensor:
    """
    Reward for reaching the target end-effector position.
    """
    robot = env.scene[asset_cfg.name]
    ee_pos = robot.data.body_pos_w[:, asset_cfg.body_ids[0]]
    target_pos = env.command_manager.get_command(command_name)[:, :3]
    distance = torch.norm(target_pos - ee_pos, dim=-1)
    # Reward is higher when distance is smaller. Scale is arbitrary but should be reasonable.
    # For 5cm tolerance, a distance of 0.05 should yield a reward of 0.
    reward = torch.exp(-5 * distance) * 10.0
    return reward

def ee_orientation_reward(env: ManagerBasedRLEnv, asset_cfg: SceneEntityCfg, command_name: str) -> torch.Tensor:
    """
    Reward for achieving the target end-effector orientation.
    """
    robot = env.scene[asset_cfg.name]
    ee_orn = robot.data.body_quat_w[:, asset_cfg.body_ids[0]]
    target_orn = env.command_manager.get_command(command_name)[:, 3:]

    # Calculate orientation difference (axis-angle representation)
    delta_orn = quat_mul(quat_inv(ee_orn), target_orn)
    # Angle is half the magnitude of the axis-angle vector.
    angle = torch.norm(delta_orn[:, 1:], dim=-1) * 2.0

    # Reward is higher when angle is smaller.
    reward = torch.exp(-5 * angle) * 10.0
    return reward

def action_rate_penalty(env: ManagerBasedRLEnv, asset_cfg: SceneEntityCfg, command_name: str) -> torch.Tensor:
    """
    Penalty for high joint velocities, encouraging smooth motion.
    """
    # Access the current and previous joint velocities
    joint_vel = env.scene[asset_cfg.name].data.joint_vel
    prev_joint_vel = env.scene[asset_cfg.name].data.prev_joint_vel
    
    # Calculate the difference in joint velocities
    vel_diff = joint_vel - prev_joint_vel
    
    # Square the difference and sum, then take the mean for each environment
    # A common approach is to penalize the L2 norm of the velocity changes.
    penalty = torch.mean(vel_diff**2, dim=-1)
    
    # The penalty should be a negative reward. Scale can be tuned.
    return -penalty * 0.1


# --- LLM GENERATED FUNCTIONS END ---

def get_reward_cfg(env_cfg, robot_ee_body_name: str):
    """
    This function is called by reach_task.py to inject 
    the generated rewards into the Environment Config.
    """
    
    # We define the specific rewards here based on what the LLM created.
    # The LLM will be instructed to provide a dictionary called 'generated_terms'
    
    reward_dict = {
    "RewTerm": RewTerm.from_function(
        func=ee_position_reward,
        env=env,
        asset_cfg=SceneEntityCfg(name="franka", body_names=["panda_hand"]),
        command_name="ee_pose"
    ),
    "RewTerm": RewTerm.from_function(
        func=ee_orientation_reward,
        env=env,
        asset_cfg=SceneEntityCfg(name="franka", body_names=["panda_hand"]),
        command_name="ee_pose"
    ),
    "RewTerm": RewTerm.from_function(
        func=action_rate_penalty,
        env=env,
        asset_cfg=SceneEntityCfg(name="franka", body_names=["panda_hand"]), # Assuming this asset_cfg is valid for the robot
        command_name="ee_pose" # Command name is not directly used but required by signature
    )
}
    
    # Example of what the LLM should generate:
    # reward_dict = {
    #     "reaching_goal": RewTerm(
    #         func=rew_function_name, # One of the functions inserted above
    #         weight=1.0,
    #         params={"asset_cfg": SceneEntityCfg("robot", body_names=[robot_ee_body_name]), "command_name": "ee_pose"}
    #     ),
    # }
    
    return reward_dict

def compute_success(env: ManagerBasedRLEnv) -> torch.Tensor:
    """
    Standardized success check. Automatically finds the EE index 
    using the body name from the robot configuration.
    """
    # 1. Get Target
    target_pos = env.command_manager.get_command("ee_pose")[:, :3]
    
    # 2. Dynamic EE Indexing
    # Instead of hardcoding '0', we find the index of 'panda_hand' or 'ee_link'
    robot = env.scene["robot"]
    
    # This matches the 'ee_body_name' passed in from reach.yaml
    # We use a simple search or pass it through the env_cfg
    ee_name = env.cfg.robot_ee_body_name # We'll ensure this is set in get_reward_cfg
    ee_index, _ = robot.find_bodies(ee_name)
    
    # 3. Get World Position of that specific index
    ee_pos = robot.data.body_pos_w[:, ee_index[0]] 
    
    # 4. Calculate Distance and Return
    distance = torch.norm(target_pos - ee_pos, dim=-1)
    return (distance < 0.05).float()