import torch
import torch.nn as nn
from isaaclab.envs import ManagerBasedRLEnv
from isaaclab.managers import RewardTermCfg as RewTerm
from isaaclab.managers import SceneEntityCfg
import isaaclab_tasks.manager_based.manipulation.reach.mdp as mdp

# --- LLM GENERATED FUNCTIONS START ---
# This section will be populated by 1_eureka.py 
# using the functions generated by the LLM.

def ee_position_distance_reward(env: ManagerBasedRLEnv, asset_cfg: SceneEntityCfg, command_name: str) -> torch.Tensor:
    """
    Reward for end-effector staying close to the target position.
    """
    robot = env.scene[asset_cfg.name]
    ee_pos = robot.data.body_pos_w[:, asset_cfg.body_ids[0]]
    target_pos = env.command_manager.get_command(command_name)[:, :3]
    distance = torch.norm(target_pos - ee_pos, dim=-1)
    # Reward is inversely proportional to distance, scaled down to avoid dominating other rewards
    return torch.exp(-distance * 5.0) * 0.1 # Scale factor of 5.0 and weight of 0.1

def ee_orientation_reward(env: ManagerBasedRLEnv, asset_cfg: SceneEntityCfg, command_name: str) -> torch.Tensor:
    """
    Reward for end-effector matching the target orientation.
    """
    robot = env.scene[asset_cfg.name]
    ee_rot_w = robot.data.body_quat_w[:, asset_cfg.body_ids[0]]
    target_rot_w = env.command_manager.get_command(command_name)[:, 3:]

    # Calculate orientation difference (quaternion)
    # We want to match the target orientation, so the difference should be close to identity (0,0,0,1)
    # or the negative of identity (0,0,0,-1) if the target is defined as such.
    # For simplicity, let's assume target_rot_w is in the same convention as ee_rot_w.
    # The shortest path between two quaternions q1 and q2 is often measured by |q1 * conjugate(q2)|.
    # A value close to 1 indicates similar orientations.
    orientation_error = quat_conjugate(ee_rot_w) * target_rot_w
    # Get the scalar part of the quaternion, which should be close to 1 for matching orientations.
    # Clamp it to avoid issues with quaternion math and ensure it's between 0 and 1.
    similarity = torch.clamp(orientation_error.w, min=0.0, max=1.0)

    # Reward is high when similarity is high (close to 1)
    return similarity * 0.5 # Weight of 0.5

def action_rate_penalty(env: ManagerBasedRLEnv, asset_cfg: SceneEntityCfg) -> torch.Tensor:
    """
    Penalizes large changes in joint velocities (smoothness).
    """
    # Get current and previous joint velocities
    current_joint_vel = env.scene[asset_cfg.name].data.joint_vel
    # Accessing prev_joint_vel requires storing it from the previous step,
    # which is not directly available in this function signature without modifying the env.
    # For this example, we will approximate by penalizing the magnitude of current joint velocities.
    # A more accurate solution would involve storing previous velocities.
    # If the state includes joint velocities, we can use that directly.
    # Assuming 'joint_vel' is available in robot.data

    # Penalize the squared magnitude of joint velocities
    # Lower velocities lead to higher reward (less penalty)
    return -torch.sum(current_joint_vel**2, dim=-1) * 0.01 # Weight of 0.01

def success_reward(env: ManagerBasedRLEnv, asset_cfg: SceneEntityCfg, command_name: str) -> torch.Tensor:
    """
    Provides a dense reward for being close to the target, with a bonus for achieving success.
    """
    robot = env.scene[asset_cfg.name]
    ee_pos = robot.data.body_pos_w[:, asset_cfg.body_ids[0]]
    target_pos = env.command_manager.get_command(command_name)[:, :3]

    distance = torch.norm(target_pos - ee_pos, dim=-1)

    # Reward for being within 5cm, proportional to how close it is.
    # Maximum reward if distance is 0, scales down as distance increases.
    # Only provide positive reward if within a certain threshold (e.g., 0.1m) to encourage progress.
    position_reward = torch.where(distance < 0.1, torch.exp(-distance * 10.0), torch.zeros_like(distance))

    # Bonus for achieving the success criteria (within 5cm and correct orientation)
    ee_rot_w = robot.data.body_quat_w[:, asset_cfg.body_ids[0]]
    target_rot_w = env.command_manager.get_command(command_name)[:, 3:]
    orientation_error = quat_conjugate(ee_rot_w) * target_rot_w
    similarity = torch.clamp(orientation_error.w, min=0.0, max=1.0)
    orientation_match = (similarity > 0.98) # Threshold for orientation match

    success_threshold_pos = 0.05  # 5cm
    success_pos = (distance < success_threshold_pos)
    is_successful = success_pos & orientation_match

    # Add a significant bonus for successful completion
    success_bonus = torch.where(is_successful, torch.ones_like(distance) * 1.0, torch.zeros_like(distance))

    return position_reward * 0.2 + success_bonus # Combined position reward and success bonus



# --- LLM GENERATED FUNCTIONS END ---

def get_reward_cfg(env_cfg, robot_ee_body_name: str):
    """
    This function is called by reach_task.py to inject 
    the generated rewards into the Environment Config.
    """
    
    # We define the specific rewards here based on what the LLM created.
    # The LLM will be instructed to provide a dictionary called 'generated_terms'
    
    reward_dict = {
    "ee_position_distance": RewTerm(func=ee_position_distance_reward, params={"asset_cfg": SceneEntityCfg(name="robot", body_names=["panda_hand"]), "command_name": "reach_target"}),
    "ee_orientation": RewTerm(func=ee_orientation_reward, params={"asset_cfg": SceneEntityCfg(name="robot", body_names=["panda_hand"]), "command_name": "reach_target"}),
    "action_rate": RewTerm(func=action_rate_penalty, params={"asset_cfg": SceneEntityCfg(name="robot", body_names=["panda_hand"])}),
    "success_reward": RewTerm(func=success_reward, params={"asset_cfg": SceneEntityCfg(name="robot", body_names=["panda_hand"]), "command_name": "reach_target"})
}
    
    # Example of what the LLM should generate:
    # reward_dict = {
    #     "reaching_goal": RewTerm(
    #         func=rew_function_name, # One of the functions inserted above
    #         weight=1.0,
    #         params={"asset_cfg": SceneEntityCfg("robot", body_names=[robot_ee_body_name]), "command_name": "ee_pose"}
    #     ),
    # }
    
    return reward_dict

def compute_success(env: ManagerBasedRLEnv) -> torch.Tensor:
    """
    Standardized success check. Automatically finds the EE index 
    using the body name from the robot configuration.
    """
    # 1. Get Target
    target_pos = env.command_manager.get_command("ee_pose")[:, :3]
    
    # 2. Dynamic EE Indexing
    # Instead of hardcoding '0', we find the index of 'panda_hand' or 'ee_link'
    robot = env.scene["robot"]
    
    # This matches the 'ee_body_name' passed in from reach.yaml
    # We use a simple search or pass it through the env_cfg
    ee_name = env.cfg.robot_ee_body_name # We'll ensure this is set in get_reward_cfg
    ee_index, _ = robot.find_bodies(ee_name)
    
    # 3. Get World Position of that specific index
    ee_pos = robot.data.body_pos_w[:, ee_index[0]] 
    
    # 4. Calculate Distance and Return
    distance = torch.norm(target_pos - ee_pos, dim=-1)
    return (distance < 0.05).float()