import torch
import torch.nn as nn
from isaaclab.envs import ManagerBasedRLEnv
from isaaclab.managers import RewardTermCfg as RewTerm
from isaaclab.managers import SceneEntityCfg
import isaaclab_tasks.manager_based.manipulation.reach.mdp as mdp

# --- LLM GENERATED FUNCTIONS START ---
# This section will be populated by 1_eureka.py 
# using the functions generated by the LLM.

def reward_func_dist_to_target(env: ManagerBasedRLEnv, asset_cfg: SceneEntityCfg, command_name: str) -> torch.Tensor:
    """
    Reward for distance to target position.
    """
    robot = env.scene[asset_cfg.name]
    ee_pos = robot.data.body_pos_w[:, asset_cfg.body_ids[0]]
    target_pos = env.command_manager.get_command(command_name)[:, :3]
    distance = torch.norm(target_pos - ee_pos, dim=-1)
    # Reward is inversely proportional to distance, with a maximum reward for being within 5cm
    max_reward = 1.0
    min_dist_threshold = 0.05  # 5cm
    reward = torch.exp(-distance / min_dist_threshold) * max_reward
    return reward

def reward_func_orientation_mismatch(env: ManagerBasedRLEnv, asset_cfg: SceneEntityCfg, command_name: str) -> torch.Tensor:
    """
    Reward for orientation alignment.
    """
    robot = env.scene[asset_cfg.name]
    ee_orn_w = robot.data.body_orn_w[:, asset_cfg.body_ids[0]]
    target_orn = env.command_manager.get_command(command_name)[:, 3:] # Assuming orientation is next 4 values

    # Convert to axis-angle for easier comparison
    orientation_error = quat_diff_rad(ee_orn_w, target_orn)
    
    # Reward is higher when orientation error is smaller. Max reward for near perfect alignment.
    max_reward = 1.0
    max_orientation_error_rad = 0.1 # A small tolerance for orientation
    reward = torch.exp(-orientation_error / max_orientation_error_rad) * max_reward
    return reward

def reward_func_action_rate_penalty(env: ManagerBasedRLEnv, asset_cfg: SceneEntityCfg) -> torch.Tensor:
    """
    Penalty for high joint velocities.
    """
    robot = env.scene[asset_cfg.name]
    joint_vel = robot.data.joint_vel
    # Penalize large joint velocities to encourage smooth motion
    max_vel = 5.0 # Example maximum allowed joint velocity (rad/s)
    penalty = torch.sum(torch.square(joint_vel / max_vel), dim=-1)
    return -penalty

def reward_func_ee_vel_penalty(env: ManagerBasedRLEnv, asset_cfg: SceneEntityCfg) -> torch.Tensor:
    """
    Penalty for high end-effector linear velocity.
    """
    robot = env.scene[asset_cfg.name]
    ee_lin_vel_w = robot.data.body_lin_vel_w[:, asset_cfg.body_ids[0]]
    max_lin_vel = 1.0 # Example maximum allowed end-effector linear velocity (m/s)
    penalty = torch.sum(torch.square(ee_lin_vel_w / max_lin_vel), dim=-1)
    return -penalty

# Helper function for quaternion difference (assuming it's available in the environment context or imported)
# If not, a direct implementation or a call to a utility like isaaclab.utils.math.quat_diff_rad would be needed.
# For this example, we'll assume it's accessible or defined elsewhere.
# Example placeholder:
# def quat_diff_rad(q1, q2):
#     # Replace with actual quaternion difference calculation if not available
#     return 2 * torch.acos(torch.abs(torch.sum(q1 * q2, dim=-1)))


# --- LLM GENERATED FUNCTIONS END ---

def get_reward_cfg(env_cfg, robot_ee_body_name: str):
    """
    This function is called by reach_task.py to inject 
    the generated rewards into the Environment Config.
    """
    
    # We define the specific rewards here based on what the LLM created.
    # The LLM will be instructed to provide a dictionary called 'generated_terms'
    
    reward_dict = {
    "dist_to_target": RewTerm(func=reward_func_dist_to_target, weight=1.0, params={"asset_cfg": SceneEntityCfg("franka", body_names=["panda_hand"]), "command_name": "ee_pose"}),
    "orientation_mismatch": RewTerm(func=reward_func_orientation_mismatch, weight=1.0, params={"asset_cfg": SceneEntityCfg("franka", body_names=["panda_hand"]), "command_name": "ee_pose"}),
    "action_rate_penalty": RewTerm(func=reward_func_action_rate_penalty, weight=0.1, params={"asset_cfg": SceneEntityCfg("franka", body_names=["panda_hand"])}),
    "ee_vel_penalty": RewTerm(func=reward_func_ee_vel_penalty, weight=0.05, params={"asset_cfg": SceneEntityCfg("franka", body_names=["panda_hand"])}),
}
    
    # Example of what the LLM should generate:
    # reward_dict = {
    #     "reaching_goal": RewTerm(
    #         func=rew_function_name, # One of the functions inserted above
    #         weight=1.0,
    #         params={"asset_cfg": SceneEntityCfg("robot", body_names=[robot_ee_body_name]), "command_name": "ee_pose"}
    #     ),
    # }
    
    return reward_dict

def compute_success(env: ManagerBasedRLEnv) -> torch.Tensor:
    """
    Standardized success check. Automatically finds the EE index 
    using the body name from the robot configuration.
    """
    # 1. Get Target
    target_pos = env.command_manager.get_command("ee_pose")[:, :3]
    
    # 2. Dynamic EE Indexing
    # Instead of hardcoding '0', we find the index of 'panda_hand' or 'ee_link'
    robot = env.scene["robot"]
    
    # This matches the 'ee_body_name' passed in from reach.yaml
    # We use a simple search or pass it through the env_cfg
    ee_name = env.cfg.robot_ee_body_name # We'll ensure this is set in get_reward_cfg
    ee_index, _ = robot.find_bodies(ee_name)
    
    # 3. Get World Position of that specific index
    ee_pos = robot.data.body_pos_w[:, ee_index[0]] 
    
    # 4. Calculate Distance and Return
    distance = torch.norm(target_pos - ee_pos, dim=-1)
    return (distance < 0.05).float()