"""
Domain Randomization configuration.

This file is auto-generated by 3_dr_eureka.py using template injection.
The LLM-generated parameter ranges are inserted below.

Each variable should be named `<param>_range` and contain a two-element list
[low, high]. eval_headless.py loads this file and applies these ranges as
event terms that sample fresh values on every episode reset.
"""

joint_friction_range = [0.1, 3.0]
joint_armature_range = [0.0, 0.5]
joint_stiffness_scale_range = [0.7, 1.3]
joint_damping_scale_range = [0.7, 1.3]